--
-- PostgreSQL database dump
--

\restrict ZM7MNcO4Bpmv0N0tMcI6TO9jGeBHk7udhDXMGWjfsc8mKqxoD8BaBatScI90ACs

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.user_anime_lists DROP CONSTRAINT IF EXISTS fkqk3vjt6m0sgyfr6x19qixtbjn;
ALTER TABLE IF EXISTS ONLY public.games DROP CONSTRAINT IF EXISTS fkgas7amj76041l6b8nqlx4mrvx;
ALTER TABLE IF EXISTS ONLY public.downloads DROP CONSTRAINT IF EXISTS fk82a9lrpyjtlyxrtcndge5nrt9;
ALTER TABLE IF EXISTS ONLY public.episodes DROP CONSTRAINT IF EXISTS fk541d3nal2nkx8usn6c742plcr;
ALTER TABLE IF EXISTS ONLY public.user_anime_lists DROP CONSTRAINT IF EXISTS fk37dp5tbgf8wmfsdy6s3dwrbst;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.user_anime_lists DROP CONSTRAINT IF EXISTS user_anime_lists_pkey;
ALTER TABLE IF EXISTS ONLY public.categories DROP CONSTRAINT IF EXISTS ukt8o6pivur7nn124jehx7cygw5;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS ukr43af9ap4edm43mmtq01oddj6;
ALTER TABLE IF EXISTS ONLY public.user_anime_lists DROP CONSTRAINT IF EXISTS ukh3qngku8eshwy3khse4synrhh;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.news DROP CONSTRAINT IF EXISTS news_pkey;
ALTER TABLE IF EXISTS ONLY public.guides DROP CONSTRAINT IF EXISTS guides_pkey;
ALTER TABLE IF EXISTS ONLY public.games DROP CONSTRAINT IF EXISTS games_pkey;
ALTER TABLE IF EXISTS ONLY public.episodes DROP CONSTRAINT IF EXISTS episodes_pkey;
ALTER TABLE IF EXISTS ONLY public.downloads DROP CONSTRAINT IF EXISTS downloads_pkey;
ALTER TABLE IF EXISTS ONLY public.categories DROP CONSTRAINT IF EXISTS categories_pkey;
ALTER TABLE IF EXISTS ONLY public.animes DROP CONSTRAINT IF EXISTS animes_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.user_anime_lists;
DROP TABLE IF EXISTS public.news;
DROP TABLE IF EXISTS public.guides;
DROP TABLE IF EXISTS public.games;
DROP TABLE IF EXISTS public.episodes;
DROP TABLE IF EXISTS public.downloads;
DROP TABLE IF EXISTS public.categories;
DROP TABLE IF EXISTS public.animes;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: animes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.animes (
    id bigint NOT NULL,
    banner_url character varying(255),
    end_date date,
    favorite_count integer,
    genres character varying(500),
    is_featured boolean,
    poster_url character varying(255),
    rating double precision,
    release_date date,
    status character varying(255),
    studio character varying(255),
    synopsis character varying(2000),
    tags character varying(500),
    title_english character varying(255),
    title_japanese character varying(255) NOT NULL,
    title_romaji character varying(255) NOT NULL,
    total_episodes integer,
    trailer_url character varying(255),
    type character varying(255),
    view_count integer,
    CONSTRAINT animes_status_check CHECK (((status)::text = ANY ((ARRAY['AIRING'::character varying, 'FINISHED'::character varying, 'UPCOMING'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT animes_type_check CHECK (((type)::text = ANY ((ARRAY['TV'::character varying, 'MOVIE'::character varying, 'OVA'::character varying, 'ONA'::character varying, 'SPECIAL'::character varying])::text[])))
);


ALTER TABLE public.animes OWNER TO postgres;

--
-- Name: animes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.animes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    color_code character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(500),
    display_order integer,
    icon_class character varying(255),
    is_active boolean,
    name character varying(255) NOT NULL,
    slug character varying(255),
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: downloads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.downloads (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    download_count integer,
    download_type character varying(255),
    download_url character varying(255) NOT NULL,
    file_size character varying(255),
    is_official boolean,
    notes character varying(255),
    platform character varying(255),
    requires_account boolean,
    updated_at timestamp(6) without time zone,
    version character varying(255),
    game_id bigint NOT NULL
);


ALTER TABLE public.downloads OWNER TO postgres;

--
-- Name: downloads_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.downloads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.downloads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: episodes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.episodes (
    id bigint NOT NULL,
    description character varying(1000),
    duration integer,
    episode_number integer NOT NULL,
    release_date date,
    server_urls character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    video_url character varying(255),
    view_count integer,
    anime_id bigint NOT NULL
);


ALTER TABLE public.episodes OWNER TO postgres;

--
-- Name: episodes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.episodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.episodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    badge character varying(255),
    badge_color character varying(255),
    cover_image_url character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(3000),
    developer character varying(255),
    download_count integer,
    genre character varying(255),
    is_featured boolean,
    platforms character varying(255),
    publisher character varying(255),
    rating double precision,
    release_date date,
    short_description character varying(500),
    thumbnail_url character varying(255),
    title character varying(255) NOT NULL,
    trailer_url character varying(255),
    updated_at timestamp(6) without time zone,
    view_count integer,
    category_id bigint
);


ALTER TABLE public.games OWNER TO postgres;

--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guides; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.guides (
    id bigint NOT NULL,
    category character varying(255),
    content character varying(3000),
    created_at timestamp(6) without time zone,
    description character varying(500),
    difficulty_level character varying(255),
    estimated_time character varying(255),
    guide_url character varying(255),
    icon_class character varying(255),
    icon_gradient character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count integer
);


ALTER TABLE public.guides OWNER TO postgres;

--
-- Name: guides_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.guides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guides_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    author character varying(255),
    category character varying(255),
    content character varying(2000),
    created_at timestamp(6) without time zone,
    icon_class character varying(255),
    icon_color character varying(255),
    image_url character varying(255),
    news_url character varying(255),
    published_at timestamp(6) without time zone,
    summary character varying(500),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.news OWNER TO postgres;

--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_anime_lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_anime_lists (
    id bigint NOT NULL,
    added_date timestamp(6) without time zone,
    episodes_watched integer,
    is_favorite boolean,
    notes character varying(1000),
    updated_date timestamp(6) without time zone,
    user_rating double precision,
    watch_status character varying(255) NOT NULL,
    anime_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_anime_lists_watch_status_check CHECK (((watch_status)::text = ANY ((ARRAY['WATCHING'::character varying, 'COMPLETED'::character varying, 'ON_HOLD'::character varying, 'DROPPED'::character varying, 'PLAN_TO_WATCH'::character varying])::text[])))
);


ALTER TABLE public.user_anime_lists OWNER TO postgres;

--
-- Name: user_anime_lists_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_anime_lists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_anime_lists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255),
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: animes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.animes (id, banner_url, end_date, favorite_count, genres, is_featured, poster_url, rating, release_date, status, studio, synopsis, tags, title_english, title_japanese, title_romaji, total_episodes, trailer_url, type, view_count) FROM stdin;
1	\N	\N	0	\N	\N	\N	9.5	\N	AIRING	\N	Aventuras de Monkey D. Luffy y su tripulación	\N	One Piece	ワンピース	One Piece	\N	\N	TV	0
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, color_code, created_at, description, display_order, icon_class, is_active, name, slug, updated_at) FROM stdin;
1	#FF5733	2025-12-19 16:38:50.793942	Juegos de acción y aventura	0	fa-fire	t	Acción	acción	2025-12-19 16:38:50.793942
\.


--
-- Data for Name: downloads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.downloads (id, created_at, download_count, download_type, download_url, file_size, is_official, notes, platform, requires_account, updated_at, version, game_id) FROM stdin;
\.


--
-- Data for Name: episodes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.episodes (id, description, duration, episode_number, release_date, server_urls, thumbnail_url, title, video_url, view_count, anime_id) FROM stdin;
\.


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.games (id, badge, badge_color, cover_image_url, created_at, description, developer, download_count, genre, is_featured, platforms, publisher, rating, release_date, short_description, thumbnail_url, title, trailer_url, updated_at, view_count, category_id) FROM stdin;
\.


--
-- Data for Name: guides; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.guides (id, category, content, created_at, description, difficulty_level, estimated_time, guide_url, icon_class, icon_gradient, title, updated_at, view_count) FROM stdin;
\.


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news (id, author, category, content, created_at, icon_class, icon_color, image_url, news_url, published_at, summary, title, updated_at) FROM stdin;
\.


--
-- Data for Name: user_anime_lists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_anime_lists (id, added_date, episodes_watched, is_favorite, notes, updated_date, user_rating, watch_status, anime_id, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, avatar_url, created_at, email, name, password, role, username) FROM stdin;
2	\N	2025-12-20 01:38:25.657349	eduardo_alejandro_johnson@hotmail.com	Eduardo Johnson	Colisagay1214	USER	eduardo_alejandro_johnson
3	\N	2025-12-20 01:59:38.808187	mjohnson@gmail.com	Liliana Guerrero	123456	USER	Liliana123
4	\N	2025-12-20 02:21:29.836967	eduardooh123@gmail.com	Eduardo Johnson	$2a$10$v9dJ5ctNrAeEh4Pzf6lFeOx8PbvKiDlbaBE4QFhxbFXdTGZXwBO86	USER	eduardoohh
\.


--
-- Name: animes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.animes_id_seq', 1, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, true);


--
-- Name: downloads_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.downloads_id_seq', 1, false);


--
-- Name: episodes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.episodes_id_seq', 1, false);


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.games_id_seq', 1, false);


--
-- Name: guides_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.guides_id_seq', 1, false);


--
-- Name: news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.news_id_seq', 1, false);


--
-- Name: user_anime_lists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_anime_lists_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: animes animes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.animes
    ADD CONSTRAINT animes_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: downloads downloads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.downloads
    ADD CONSTRAINT downloads_pkey PRIMARY KEY (id);


--
-- Name: episodes episodes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.episodes
    ADD CONSTRAINT episodes_pkey PRIMARY KEY (id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: guides guides_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.guides
    ADD CONSTRAINT guides_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_anime_lists ukh3qngku8eshwy3khse4synrhh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_anime_lists
    ADD CONSTRAINT ukh3qngku8eshwy3khse4synrhh UNIQUE (user_id, anime_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: user_anime_lists user_anime_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_anime_lists
    ADD CONSTRAINT user_anime_lists_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_anime_lists fk37dp5tbgf8wmfsdy6s3dwrbst; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_anime_lists
    ADD CONSTRAINT fk37dp5tbgf8wmfsdy6s3dwrbst FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: episodes fk541d3nal2nkx8usn6c742plcr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.episodes
    ADD CONSTRAINT fk541d3nal2nkx8usn6c742plcr FOREIGN KEY (anime_id) REFERENCES public.animes(id);


--
-- Name: downloads fk82a9lrpyjtlyxrtcndge5nrt9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.downloads
    ADD CONSTRAINT fk82a9lrpyjtlyxrtcndge5nrt9 FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: games fkgas7amj76041l6b8nqlx4mrvx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT fkgas7amj76041l6b8nqlx4mrvx FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: user_anime_lists fkqk3vjt6m0sgyfr6x19qixtbjn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_anime_lists
    ADD CONSTRAINT fkqk3vjt6m0sgyfr6x19qixtbjn FOREIGN KEY (anime_id) REFERENCES public.animes(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ZM7MNcO4Bpmv0N0tMcI6TO9jGeBHk7udhDXMGWjfsc8mKqxoD8BaBatScI90ACs

