services:
  - type: web
    name: prueba-sprint-api
    env: java
    rootDir: prueba-sprint
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/prueba-sprint-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: postgresql://postgres.htdvrcajzddfjzpbfjhb:Colisagay1214@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
