-- Esquema inicial de la base de datos
-- Tablas: animes, categories, downloads, episodes, games, guides, news, user_anime_lists, users

-- Tabla: animes
CREATE TABLE IF NOT EXISTS public.animes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_url character varying(255),
    end_date date,
    favorite_count integer,
    genres character varying(500),
    is_featured boolean,
    poster_url character varying(255),
    rating double precision,
    release_date date,
    status character varying(255),
    studio character varying(255),
    synopsis character varying(2000),
    tags character varying(500),
    title_english character varying(255),
    title_japanese character varying(255) NOT NULL,
    title_romaji character varying(255) NOT NULL,
    total_episodes integer,
    trailer_url character varying(255),
    type character varying(255),
    view_count integer,
    CONSTRAINT animes_status_check CHECK (((status)::text = ANY ((ARRAY['AIRING'::character varying, 'FINISHED'::character varying, 'UPCOMING'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT animes_type_check CHECK (((type)::text = ANY ((ARRAY['TV'::character varying, 'MOVIE'::character varying, 'OVA'::character varying, 'ONA'::character varying, 'SPECIAL'::character varying])::text[])))
);

-- Tabla: categories
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color_code character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(500),
    display_order integer,
    icon_class character varying(255),
    is_active boolean,
    name character varying(255) NOT NULL UNIQUE,
    slug character varying(255),
    updated_at timestamp(6) without time zone
);

-- Tabla: games
CREATE TABLE IF NOT EXISTS public.games (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    badge character varying(255),
    badge_color character varying(255),
    cover_image_url character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(3000),
    developer character varying(255),
    download_count integer,
    genre character varying(255),
    is_featured boolean,
    platforms character varying(255),
    publisher character varying(255),
    rating double precision,
    release_date date,
    short_description character varying(500),
    thumbnail_url character varying(255),
    title character varying(255) NOT NULL,
    trailer_url character varying(255),
    updated_at timestamp(6) without time zone,
    view_count integer,
    category_id bigint REFERENCES public.categories(id)
);

-- Tabla: downloads
CREATE TABLE IF NOT EXISTS public.downloads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    download_count integer,
    download_type character varying(255),
    download_url character varying(255) NOT NULL,
    file_size character varying(255),
    is_official boolean,
    notes character varying(255),
    platform character varying(255),
    requires_account boolean,
    updated_at timestamp(6) without time zone,
    version character varying(255),
    game_id bigint NOT NULL REFERENCES public.games(id)
);

-- Tabla: episodes
CREATE TABLE IF NOT EXISTS public.episodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(1000),
    duration integer,
    episode_number integer NOT NULL,
    release_date date,
    server_urls character varying(255),
    thumbnail_url character varying(255),
    title character varying(255),
    video_url character varying(255),
    view_count integer,
    anime_id bigint NOT NULL REFERENCES public.animes(id)
);

-- Tabla: guides
CREATE TABLE IF NOT EXISTS public.guides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category character varying(255),
    content character varying(3000),
    created_at timestamp(6) without time zone,
    description character varying(500),
    difficulty_level character varying(255),
    estimated_time character varying(255),
    guide_url character varying(255),
    icon_class character varying(255),
    icon_gradient character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count integer
);

-- Tabla: news
CREATE TABLE IF NOT EXISTS public.news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author character varying(255),
    category character varying(255),
    content character varying(2000),
    created_at timestamp(6) without time zone,
    icon_class character varying(255),
    icon_color character varying(255),
    image_url character varying(255),
    news_url character varying(255),
    published_at timestamp(6) without time zone,
    summary character varying(500),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);

-- Tabla: users
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avatar_url character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL UNIQUE,
    name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255),
    username character varying(255) NOT NULL UNIQUE
);

-- Tabla: user_anime_lists
CREATE TABLE IF NOT EXISTS public.user_anime_lists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    added_date timestamp(6) without time zone,
    episodes_watched integer,
    is_favorite boolean,
    notes character varying(1000),
    updated_date timestamp(6) without time zone,
    user_rating double precision,
    watch_status character varying(255) NOT NULL,
    anime_id bigint NOT NULL REFERENCES public.animes(id),
    user_id bigint NOT NULL REFERENCES public.users(id),
    CONSTRAINT ukh3qngku8eshwy3khse4synrhh UNIQUE (user_id, anime_id),
    CONSTRAINT user_anime_lists_watch_status_check CHECK (((watch_status)::text = ANY ((ARRAY['WATCHING'::character varying, 'COMPLETED'::character varying, 'ON_HOLD'::character varying, 'DROPPED'::character varying, 'PLAN_TO_WATCH'::character varying])::text[])))
);

-- Datos iniciales: animes
INSERT INTO public.animes (id, banner_url, end_date, favorite_count, genres, is_featured, poster_url, rating, release_date, status, studio, synopsis, tags, title_english, title_japanese, title_romaji, total_episodes, trailer_url, type, view_count)
VALUES (1, NULL, NULL, 0, NULL, NULL, NULL, 9.5, NULL, 'AIRING', NULL, 'Aventuras de Monkey D. Luffy y su tripulación', NULL, 'One Piece', 'ワンピース', 'One Piece', NULL, NULL, 'TV', 0)
ON CONFLICT (id) DO NOTHING;

-- Datos iniciales: categories
INSERT INTO public.categories (id, color_code, created_at, description, display_order, icon_class, is_active, name, slug, updated_at)
VALUES (1, '#FF5733', '2025-12-19 16:38:50.793942', 'Juegos de acción y aventura', 0, 'fa-fire', true, 'Acción', 'acción', '2025-12-19 16:38:50.793942')
ON CONFLICT (id) DO NOTHING;

-- Datos iniciales: users
INSERT INTO public.users (id, avatar_url, created_at, email, name, password, role, username)
VALUES 
(2, NULL, '2025-12-20 01:38:25.657349', 'eduardo_alejandro_johnson@hotmail.com', 'Eduardo Johnson', 'Colisagay1214', 'USER', 'eduardo_alejandro_johnson'),
(3, NULL, '2025-12-20 01:59:38.808187', 'mjohnson@gmail.com', 'Liliana Guerrero', '123456', 'USER', 'Liliana123'),
(4, NULL, '2025-12-20 02:21:29.836967', 'eduardooh123@gmail.com', 'Eduardo Johnson', '$2a$10$v9dJ5ctNrAeEh4Pzf6lFeOx8PbvKiDlbaBE4QFhxbFXdTGZXwBO86', 'USER', 'eduardoohh')
ON CONFLICT (id) DO NOTHING;

-- Ajustar secuencias
SELECT pg_catalog.setval('public.animes_id_seq', 1, true);
SELECT pg_catalog.setval('public.categories_id_seq', 1, true);
SELECT pg_catalog.setval('public.users_id_seq', 4, true);

